name: CI/CD Production Environment

on:
  push:
    branches:
      - prod

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Login to Private Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ secrets.REGISTRY_URL }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Backend
        uses: docker/build-push-action@v5
        with:
          context: ./backend
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/loeitech-backend:prod

      - name: Build and Push Frontend
        uses: docker/build-push-action@v5
        with:
          context: ./frontend
          push: true
          tags: ${{ secrets.REGISTRY_URL }}/loeitech-frontend:prod
          build-args: |
            VITE_API_URL=https://api-admission.loeitech.ac.th

      - name: Deploy to Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_IP }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 223
          script: |
            cd /home/adm1n_ltc/loeitech-admission \
            STACK_NAME=ltc-admission-prod \
            IMAGE_TAG=prod \
            BACKEND_PORT=3001 \
            FRONTEND_PORT=5173 \
            REGISTRY_URL=${{ secrets.REGISTRY_URL }} \
            DATABASE_URL=${{ secrets.DATABASE_URL_PROD }} \
            JWT_SECRET=${{ secrets.JWT_SECRET_PROD }} \
            FRONTEND_URL=https://admission.loeitech.ac.th \
            ./deploy.sh
